// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelManager.Infrastructure.Data;

#nullable disable

namespace TravelManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604175518_AddChecklistTemplatesWithData")]
    partial class AddChecklistTemplatesWithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "cs-role-admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-user",
                            ConcurrencyStamp = "cs-role-user",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BookingReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BookingStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("TripId");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BookingStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Not Booked"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Confirmed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Документи, одяг, гігієна, електроніка",
                            IconClass = "bi-backpack4-fill",
                            Title = "Базовий пакувальний список"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Все для відпочинку біля моря",
                            IconClass = "bi-umbrella-fill",
                            Title = "Пляжна відпустка"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Документи, ноутбук, ділові матеріали",
                            IconClass = "bi-briefcase-fill",
                            Title = "Бізнес-поїздка"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Спорядження, медикаменти, їжа",
                            IconClass = "bi-tree-fill",
                            Title = "Гірський похід"
                        });
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ChecklistTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.ToTable("ChecklistTemplateItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChecklistTemplateId = 1,
                            Content = "Паспорт / ID-картка",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ChecklistTemplateId = 1,
                            Content = "Квитки (роздруківка або PDF)",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ChecklistTemplateId = 1,
                            Content = "Страховий поліс",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ChecklistTemplateId = 1,
                            Content = "Готівка / банківська картка",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ChecklistTemplateId = 1,
                            Content = "Зарядний пристрій та кабелі",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            ChecklistTemplateId = 1,
                            Content = "Павербанк",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            ChecklistTemplateId = 1,
                            Content = "Зубна щітка та паста",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            ChecklistTemplateId = 1,
                            Content = "Шампунь / гель для душу",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            ChecklistTemplateId = 1,
                            Content = "Рушник",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            ChecklistTemplateId = 1,
                            Content = "Нижня білизна (кількість днів + 1)",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            ChecklistTemplateId = 1,
                            Content = "Шкарпетки",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            ChecklistTemplateId = 1,
                            Content = "Футболки / блузки",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            ChecklistTemplateId = 1,
                            Content = "Штани / спідниця",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            ChecklistTemplateId = 1,
                            Content = "Куртка / кофта",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            ChecklistTemplateId = 1,
                            Content = "Зручне взуття",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            ChecklistTemplateId = 1,
                            Content = "Ліки першої необхідності",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            ChecklistTemplateId = 1,
                            Content = "Навушники",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 18,
                            ChecklistTemplateId = 1,
                            Content = "Книга / планшет для дороги",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 19,
                            ChecklistTemplateId = 2,
                            Content = "Сонцезахисний крем SPF 50+",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 20,
                            ChecklistTemplateId = 2,
                            Content = "Купальник / плавки",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 21,
                            ChecklistTemplateId = 2,
                            Content = "Пляжний рушник",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 22,
                            ChecklistTemplateId = 2,
                            Content = "Сонцезахисні окуляри",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 23,
                            ChecklistTemplateId = 2,
                            Content = "Шляпа / кепка",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 24,
                            ChecklistTemplateId = 2,
                            Content = "Пляжні сандалі / в'єтнамки",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 25,
                            ChecklistTemplateId = 2,
                            Content = "Засіб від комарів",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 26,
                            ChecklistTemplateId = 2,
                            Content = "Водонепроникна сумка / чохол для телефону",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 27,
                            ChecklistTemplateId = 2,
                            Content = "Книга або електронна читалка",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 28,
                            ChecklistTemplateId = 2,
                            Content = "Пляжна парасолька / шезлонг",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 29,
                            ChecklistTemplateId = 3,
                            Content = "Ноутбук та зарядник",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 30,
                            ChecklistTemplateId = 3,
                            Content = "Візитки",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 31,
                            ChecklistTemplateId = 3,
                            Content = "Ділові документи / презентації",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 32,
                            ChecklistTemplateId = 3,
                            Content = "Ручка та блокнот",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 33,
                            ChecklistTemplateId = 3,
                            Content = "Ділове вбрання (костюм / плаття)",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 34,
                            ChecklistTemplateId = 3,
                            Content = "Дорожній адаптер",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 35,
                            ChecklistTemplateId = 3,
                            Content = "USB-хаб",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 36,
                            ChecklistTemplateId = 3,
                            Content = "Маска для сну в літаку",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 37,
                            ChecklistTemplateId = 4,
                            Content = "Трекінгові черевики",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 38,
                            ChecklistTemplateId = 4,
                            Content = "Трекінгові палиці",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 39,
                            ChecklistTemplateId = 4,
                            Content = "Рюкзак (30-50 л)",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 40,
                            ChecklistTemplateId = 4,
                            Content = "Термобілизна",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 41,
                            ChecklistTemplateId = 4,
                            Content = "Дощовик / мембранна куртка",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 42,
                            ChecklistTemplateId = 4,
                            Content = "Аптечка першої допомоги",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 43,
                            ChecklistTemplateId = 4,
                            Content = "Компас / GPS-навігатор",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 44,
                            ChecklistTemplateId = 4,
                            Content = "Ліхтарик з запасними батарейками",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 45,
                            ChecklistTemplateId = 4,
                            Content = "Запас їжі та води на маршрут",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 46,
                            ChecklistTemplateId = 4,
                            Content = "Спальник відповідний до температури",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiptImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransitId")
                        .HasColumnType("int");

                    b.Property<int?>("TripActivityId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PayerId");

                    b.HasIndex("TransitId");

                    b.HasIndex("TripActivityId");

                    b.HasIndex("TripId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Accommodation"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ExpenseSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DebtorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("bit");

                    b.Property<decimal>("OwedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DebtorId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseSplits");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Transit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BookingStatusId")
                        .HasColumnType("int");

                    b.Property<string>("CarrierInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransitTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("TransitTypeId");

                    b.HasIndex("TripId");

                    b.ToTable("Transits");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TransitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransitTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Flight"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Train"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bus"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ferry"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReturnLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("StatusId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BookingStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("TripId");

                    b.ToTable("TripActivities");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripDestinations");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransitId")
                        .HasColumnType("int");

                    b.Property<int?>("TripActivityId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("TransitId");

                    b.HasIndex("TripActivityId");

                    b.HasIndex("TripId");

                    b.ToTable("TripDocuments");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripParticipant", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("TripId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("TripParticipants");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TripRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Organizer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Participant"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TripStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Accommodation", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.BookingStatus", "BookingStatus")
                        .WithMany()
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.Trip", "Trip")
                        .WithMany("Accommodations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Checklist", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.Trip", "Trip")
                        .WithMany("Checklists")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.Checklist", "Checklist")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ChecklistTemplateItem", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Expense", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.Accommodation", "Accommodation")
                        .WithMany()
                        .HasForeignKey("AccommodationId");

                    b.HasOne("TravelManager.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.User", "Payer")
                        .WithMany("PaidExpenses")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.Transit", "Transit")
                        .WithMany()
                        .HasForeignKey("TransitId");

                    b.HasOne("TravelManager.Domain.Entities.TripActivity", "TripActivity")
                        .WithMany()
                        .HasForeignKey("TripActivityId");

                    b.HasOne("TravelManager.Domain.Entities.Trip", "Trip")
                        .WithMany("Expenses")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Category");

                    b.Navigation("Payer");

                    b.Navigation("Transit");

                    b.Navigation("Trip");

                    b.Navigation("TripActivity");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ExpenseSplit", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.User", "Debtor")
                        .WithMany("Debts")
                        .HasForeignKey("DebtorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.Expense", "Expense")
                        .WithMany("Splits")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debtor");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Transit", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.BookingStatus", "BookingStatus")
                        .WithMany()
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.TransitType", "TransitType")
                        .WithMany()
                        .HasForeignKey("TransitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.Trip", "Trip")
                        .WithMany("Transits")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("TransitType");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Trip", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.TripStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripActivity", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.BookingStatus", "BookingStatus")
                        .WithMany()
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.Trip", "Trip")
                        .WithMany("TripActivities")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripDestination", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.Trip", "Trip")
                        .WithMany("Destinations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripDocument", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.Accommodation", "Accommodation")
                        .WithMany()
                        .HasForeignKey("AccommodationId");

                    b.HasOne("TravelManager.Domain.Entities.Transit", "Transit")
                        .WithMany()
                        .HasForeignKey("TransitId");

                    b.HasOne("TravelManager.Domain.Entities.TripActivity", "TripActivity")
                        .WithMany()
                        .HasForeignKey("TripActivityId");

                    b.HasOne("TravelManager.Domain.Entities.Trip", "Trip")
                        .WithMany("TripDocuments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Transit");

                    b.Navigation("Trip");

                    b.Navigation("TripActivity");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.TripParticipant", b =>
                {
                    b.HasOne("TravelManager.Domain.Entities.TripRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.Trip", "Trip")
                        .WithMany("Participants")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManager.Domain.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Checklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Expense", b =>
                {
                    b.Navigation("Splits");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Checklists");

                    b.Navigation("Destinations");

                    b.Navigation("Expenses");

                    b.Navigation("Participants");

                    b.Navigation("Transits");

                    b.Navigation("TripActivities");

                    b.Navigation("TripDocuments");
                });

            modelBuilder.Entity("TravelManager.Domain.Entities.User", b =>
                {
                    b.Navigation("Debts");

                    b.Navigation("PaidExpenses");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
